---
title: Exploration of subsets
author: Sasha D. Hafner
output: pdf_document
date: 2021
---

For pH effects:
```{r}
table(ds3$country, ds3$app.mthd)
dim(ds3)
```


```{r}
ggplot(ds3, aes(man.ph, e.rel.72, colour = country, shape = man.source)) +
  geom_point() +
  geom_smooth(method = lm) +
  facet_wrap(. ~ app.mthd)
```

```{r}
ggplot(ds3, aes(man.ph, e.rel.72, colour = country, shape = man.source)) +
  geom_point() +
  geom_smooth(method = lm) +
  facet_wrap(. ~ exper)
```

```{r}
ggplot(d3, aes(ct, e.rel, colour = man.ph, lty = man.source, group = pmid)) +
  geom_point() +
  geom_line() +
  facet_wrap(. ~ exper)
```

```{r}
ggplot(ds3, aes(man.ph, e.rel.72, colour = man.source, lty = factor(inst), shape = factor(inst))) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  facet_grid(. ~ app.mthd)

```

```{r}
ggplot(ds3, aes(man.ph, e.rel.72, colour = man.source, lty = factor(inst), shape = factor(inst))) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  facet_wrap(~factor(inst))

```
